package com.seroja.controller;

import com.seroja.domain.MatchInfo;
import com.seroja.domain.Stadium;
import com.seroja.repos.MatchRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

@Controller // This means that this class is a Controller // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MatchRepo matchRepo;

    @GetMapping({"/main"})
    public String greeting() {

        return "redirect:/print";
    }
    @PostMapping(path="/add")
    public String addNewMatch (@RequestParam String firstCountry, @RequestParam String secondCountry,
                               @RequestParam("date") LocalDate date) {
        MatchInfo match = new MatchInfo();
        match.setFirstCountry(firstCountry);
        match.setSecondCountry(secondCountry);
        match.setDate(date);
        matchRepo.save(match);
        return "redirect:/main";
    }

    @GetMapping(path="/print")
    public String getAllMatches(Model model) {
        Iterable<MatchInfo> matchInfos = matchRepo.findAll();
        model.addAttribute("matches", matchInfos);
        return "index";
    }

    @GetMapping("/delete/{id}")
    public String delete(@PathVariable("id") int id){
        matchRepo.deleteById(id);
        return "redirect:/main";
    }
}